# Uncomment the next line to define a global platform for your project

platform :ios, '13.2'

target 'KKdayPortal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KKdayPortal

  # UI
  pod 'SnapKit', '~> 5.0.0'

  # Firebase 
  pod 'Firebase/Core', '~> 6.12.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'

  target 'KKdayPortalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
