# Uncomment the next line to define a global platform for your project

platform :ios, '13.2'
use_frameworks!
workspace 'KKdayPortal.xcworkspace'

def shared

  # Alamofire
  pod 'Alamofire', '~> 4.9.1'


  # HTML Parsing
  pod 'SwiftSoup', '~> 2.3.0'
  pod 'HTMLString', '~> 5.0.0'


  # Twilio
  pod 'TwilioVoice', '~> 6.2.1'
  
end

target 'KKdayPortal-Open' do
  project 'KKdayPortal.xcodeproj'
  shared
end


target 'KKdayPortal-Sit' do
  project 'KKdayPortal.xcodeproj'
  shared
end


target 'KKdayPortal-Production' do
  project 'KKdayPortal.xcodeproj'
  shared
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end



